# Generated by Django 3.1.4 on 2021-07-06 11:42

import MusicPlayer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('credits', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(default='your name', max_length=255)),
                ('album', models.CharField(default='Single', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to=MusicPlayer.models.upload_location)),
            ],
        ),
    ]
