# Generated by Django 3.1.4 on 2021-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFiles',
            new_name='AudioFile',
        ),
    ]
